### ISSUE TITLE
Error: Invalid magic

### ISSUE THREAD

**Issue by hewm** [ton-org/ton-core#50]
```
Error: Invalid magic
    at parseBoc (/home/ubuntu/deploy-manual/newProject/node_modules/@ton/core/dist/boc/cell/serialization.js:160:15)
    at deserializeBoc (/home/ubuntu/deploy-manual/newProject/node_modules/@ton/core/dist/boc/cell/serialization.js:168:15)
    at Function.fromBoc (/home/ubuntu/deploy-manual/newProject/node_modules/@ton/core/dist/boc/Cell.js:34:51)
    at Function.fromBase64 (/home/ubuntu/deploy-manual/newProject/node_modules/@ton/core/dist/boc/Cell.js:41:27)
    at cellParse (/home/ubuntu/deploy-manual/newProject/node_modules/@ton-api/client/dist/client.js:2388:24)
    at prepareResponseData (/home/ubuntu/deploy-manual/newProject/node_modules/@ton-api/client/dist/client.js:2406:31)
    at /home/ubuntu/deploy-manual/newProject/node_modules/@ton-api/client/dist/client.js:2462:33
    at Array.reduce (<anonymous>)
    at prepareResponseData (/home/ubuntu/deploy-manual/newProject/node_modules/@ton-api/client/dist/client.js:2459:33)
    at /home/ubuntu/deploy-manual/newProject/node_modules/@ton-api/client/dist/client.js:2398:32

```

**Comment by Jobians** [comment]
Same error any solution?

**Comment by Jobians** [comment]
Hi! 👋 Thanks for reporting this.

### 💥 `Error: Invalid magic` – What's Going On?

This error usually means you're passing an **invalid `body`** in a TON message — likely a **string instead of a Cell**, which breaks the serialization when building or emulating the message.

---

### ✅ How to Fix It

If you're using a string comment like this:

```ts
body: "Hello TON"  // ❌ This will cause 'Invalid magic'
```

Change it to:

```ts
import { beginCell } from '@ton/core';

body: beginCell().storeStringTail("Hello TON").endCell();  // ✅ Correct
```

**Comment by devmustee** [comment]
Make sure your message body is properly serialized as a Cell. use this simple pattern to fix it.

import { beginCell } from '@ton/core';

const body = beginCell()
  .storeUint(0x12345678, 32) 
  .storeStringTail("Your message")
  .endCell();

Then pass body into your message function, not the raw string.

**Comment by verytactical** [comment]
Please provide a scenario and code that reproduces this issue. As it stands right now, it's unclear what the issue is.
